bl_info = {
    "name": "Facility - Tile Floor Generator",
    "author": "Generated by Copilot",
    "version": (0, 3, 0),
    "blender": (3, 0, 0),
    "location": "View3D > Sidebar > Facility",
    "description": "Create hex/triangle-based floors and simple corridors (uses the `facility` package).",
    "warning": "",
    "wiki_url": "",
    "category": "Add Mesh",
}

import bpy
from bpy.props import (
    IntProperty,
    FloatProperty,
    StringProperty,
    PointerProperty,
    EnumProperty,
    BoolProperty,
)
from bpy.types import (
    Operator,
    Panel,
    PropertyGroup,
)

# NOTE: This add-on expects the 'facility' package to be importable (placed in Blender's PYTHONPATH
# or installed into Blender's Python). The add-on operators import facility at execution time and
# report a friendly error if it isn't found.

class FacilitySettings(PropertyGroup):
    tile_shape: EnumProperty(
        name="Tile Shape",
        description="Type of tile to generate",
        items=(
            ('HEX', "Hexagon", "Generate hexagonal tiles"),
            ('TRIANGLE', "Triangle", "Generate equilateral triangle tiles"),
        ),
        default='HEX',
    )
    orientation: EnumProperty(
        name="Orientation",
        description="Hex orientation (pointy/flat)",
        items=(
            ('POINTY', "Pointy-top", ""),
            ('FLAT', "Flat-top", ""),
        ),
        default='POINTY',
    )
    extent_mode: EnumProperty(
        name="Extent Mode",
        description="How to create a region of tiles",
        items=(
            ('PARALLELOGRAM', "Parallelogram (axial ranges)", ""),
            ('RECTANGLE', "Rectangle (grid)", ""),
        ),
        default='RECTANGLE',
    )

    rect_width: IntProperty(name="Width", default=5, min=1)
    rect_height: IntProperty(name="Height", default=5, min=1)
    rect_origin_col: IntProperty(name="Origin Col", default=0)
    rect_origin_row: IntProperty(name="Origin Row", default=0)
    rect_use_odd: IntProperty(name="Odd offset (1=odd,0=even)", default=1, min=0, max=1)

    q_min: IntProperty(name="Q Min", default=-2)
    q_max: IntProperty(name="Q Max", default=2)
    r_min: IntProperty(name="R Min", default=-2)
    r_max: IntProperty(name="R Max", default=2)

    tile_size: FloatProperty(name="Tile Size", default=1.0, min=0.001)
    spacing: FloatProperty(name="Spacing", default=0.0, min=0.0, description="Fractional gap between tiles")

    segment_tile: BoolProperty(name="Segment Tile", default=False, description="Split hex tiles into wedge segments")
    inner_ratio: FloatProperty(name="Inner Ratio", default=0.4, min=0.0, max=0.99, description="Central hole size (hex only)")

    object_name: StringProperty(name="Object Name", default="TileFloor")

    start_q: IntProperty(name="Start Q", default=0)
    start_r: IntProperty(name="Start R", default=0)
    end_q: IntProperty(name="End Q", default=3)
    end_r: IntProperty(name="End R", default=-1)


# Operators and UI omitted here for brevity in the review stage.
# When you confirm, I'll write the full add-on operator code (the version we've been iterating on).
