"""
OBJ export helpers for facility-generated geometry.

Functions:
- write_obj_from_tiles(verts, faces, path, obj_name="TileFloor", mtl_name=None)
- write_obj_from_layout(layout, tiles, path, obj_name="TileFloor", segmented=False, inner_ratio=0.4, mtl_name=None)

verts: list of (x,y,z)
faces: list of tuples of vertex indices (0-based)
"""
from typing import List, Tuple, Optional
import os


def _write_mtl(path: str, mtl_name: str, color=(0.8, 0.8, 0.8)) -> str:
    """Write a minimal MTL file next to path with a single material named mtl_name.
    Returns the mtl filename (basename) written next to the obj.
    """
    mtl_path = os.path.splitext(path)[0] + ".mtl"
    r, g, b = color
    with open(mtl_path, "w") as f:
        f.write(f"newmtl {mtl_name}\n")
        f.write(f"Kd {r:.6f} {g:.6f} {b:.6f}\n")
    return os.path.basename(mtl_path)


def write_obj_from_tiles(verts: List[Tuple[float, float, float]],
                         faces: List[Tuple[int, ...]],
                         path: str,
                         obj_name: str = "TileFloor",
                         mtl_name: Optional[str] = None):
    """
    Write an OBJ file.
    - verts: list of (x,y,z)
    - faces: list of tuples of indices (0-based)
    - path: output .obj path
    - mtl_name: if provided, write a .mtl and reference it
    """
    dirname = os.path.dirname(path)
    if dirname and not os.path.exists(dirname):
        os.makedirs(dirname, exist_ok=True)

    if mtl_name:
        mtlfile = _write_mtl(path, mtl_name)
    else:
        mtlfile = None

    with open(path, "w") as f:
        f.write("# OBJ generated by facility.obj_generator\n")
        if mtlfile:
            f.write(f"mtllib {mtlfile}\n")
            f.write(f"usemtl {mtl_name}\n")

        f.write(f"o {obj_name}\n")
        for (x, y, z) in verts:
            f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")

        for face in faces:
            # OBJ is 1-based
            indices = " ".join(str(i + 1) for i in face)
            f.write(f"f {indices}\n")


def write_obj_from_layout(layout, tiles, path: str,
                          obj_name: str = "TileFloor",
                          segmented: bool = False,
                          inner_ratio: float = 0.4,
                          mtl_name: Optional[str] = None):
    """
    Convenience: take a layout instance (HexLayout or TriangleLayout) and a tiles iterable,
    collect verts/faces using the existing HexFloorGenerator, and write an OBJ.
    """
    # Local import because generator depends on facility package
    from .generator import HexFloorGenerator

    gen = HexFloorGenerator(layout)
    verts, faces = gen._collect_vertices_and_faces(tiles, segmented=segmented, inner_ratio=inner_ratio)
    write_obj_from_tiles(verts, faces, path, obj_name=obj_name, mtl_name=mtl_name)
