"""
Export a simple OBJ file from the facility generator.

Usage (from project root):
  python -m scripts.export_obj --shape triangle --width 6 --height 4 --out docs/models/model.obj

This script imports the facility package and uses the HexFloorGenerator._collect_vertices_and_faces
helper to obtain verts/faces and writes a plain OBJ file.
"""

from __future__ import annotations
import argparse
from typing import Iterable, Tuple, List


def write_obj(path: str, verts: List[Tuple[float,float,float]], faces: List[Tuple[int,...]]):
    with open(path, 'w') as f:
        f.write('# Generated by scripts/export_obj.py\n')
        for v in verts:
            f.write('v {:.6f} {:.6f} {:.6f}\n'.format(v[0], v[1], v[2]))
        for face in faces:
            # OBJ indices are 1-based
            f.write('f')
            for idx in face:
                f.write(' {}'.format(idx + 1))
            f.write('\n')


def build_triangles(width: int, height: int, size: float = 1.0, spacing: float = 0.0, origin_col: int = 0, origin_row: int = 0):
    from facility.triangle import TriangleLayout
    from facility.generator import HexFloorGenerator
    L = TriangleLayout(size=size, spacing=spacing, origin=(0.0, 0.0))
    tiles = L.rectangular_region(width=width, height=height, origin_col=origin_col, origin_row=origin_row)
    gen = HexFloorGenerator(L)
    verts, faces = gen._collect_vertices_and_faces(tiles, segmented=False, inner_ratio=0.0)
    return verts, faces


def build_hexes(width: int, height: int, size: float = 1.0, spacing: float = 0.0, origin_col: int = 0, origin_row: int = 0):
    from facility.hexgrid import Layout as HexLayout
    from facility.generator import HexFloorGenerator
    L = HexLayout(size=size, spacing=spacing, start_angle_deg=0.0, flat_top=False)
    tiles = L.rectangular_region(width=width, height=height, origin_col=origin_col, origin_row=origin_row, odd=True)
    gen = HexFloorGenerator(L)
    verts, faces = gen._collect_vertices_and_faces(tiles, segmented=False, inner_ratio=0.0)
    return verts, faces


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--shape', choices=('triangle','hex'), default='triangle')
    p.add_argument('--width', type=int, default=6)
    p.add_argument('--height', type=int, default=4)
    p.add_argument('--size', type=float, default=1.0)
    p.add_argument('--spacing', type=float, default=0.0)
    p.add_argument('--out', type=str, default='docs/models/model.obj')
    args = p.parse_args()

    if args.shape == 'triangle':
        verts, faces = build_triangles(args.width, args.height, size=args.size, spacing=args.spacing)
    else:
        verts, faces = build_hexes(args.width, args.height, size=args.size, spacing=args.spacing)

    write_obj(args.out, verts, faces)
    print(f'Wrote {len(verts)} verts and {len(faces)} faces to {args.out}')

if __name__ == '__main__':
    main()
